#!/bin/sh
#
#  Copyright (c) 2014 Canonical
#
#  Author: Oliver Grawert <ogra@canonical.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA
#


do_shell()
{
	adb shell "$@"
}

do_shell "mkdir -p /cache/system"

do_shell "mount -o loop /data/ubuntu.img /cache/system/"

ANDROID_DIR="/cache/system/var/lib/lxc/android/"

adb push system.img $ANDROID_DIR >/dev/null 2>&1
echo "[done]"

adb reboot
